### PR TITLE
Fixed Bar Hover

### PR DESCRIPTION
**Pull request by SoraKohaku**
Firefox Bug Fixed. Another browser. Try Fixed too.

### CODE REVIEW

**Comment by mmcc** [comment]
Thanks for the PR! I'm not sure these are necessarily the fixes I had in mind to get back to the [original state](http://blog.htbx.net/videojs-skin-twitchy/) of being Twitch-esque. I might be able to dig into this more over the weekend, but do you have an example of this running somewhere?

**Comment by mmcc** [comment]
I pushed [a PR](https://github.com/mmcc/videojs-skin-twitchy/pull/4) to fix a few of these issues. Give it a try and let me know!

**Comment by SoraKohaku** [comment]
bugskintwitchy

this Fixed for when you hover width is fixed. in new version you got 98% bar effect. and I make full of that. so when hover now is full and make it not high much. for easy way another PC problems.

**Comment by mmcc** [comment]
I'm sorry, I'm not following. Are you seeing these issues on the [example page](http://mmcc.github.com/videojs-skin-twitchy)?

Edit: Ah, I just realized I never updated the documentation. If you're pulling the files in via RawGit, you need to update the version to 2.0.1: http://cdn.rawgit.com/mmcc/videojs-skin-twitchy/v2.0.1/dist/videojs-skin-twitchy.css

**Pull request closed without merging**
